# Generated by Django 5.2.3 on 2025-06-26 02:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='announcement_files/')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcement',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AwardsNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(blank=True, null=True)),
                ('abc', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('awardee', models.CharField(blank=True, null=True)),
                ('contractamount', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('dateawarded', models.DateField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='awards_notices/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Learning and Development',
                'verbose_name_plural': 'Learning and Development',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BidOpportunities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(blank=True, null=True, verbose_name='Project Name')),
                ('ref', models.CharField(blank=True, null=True, verbose_name='Reference Number')),
                ('abc', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Approved Budget')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.URLField(blank=True, null=True, verbose_name='Online Link')),
                ('file', models.FileField(blank=True, null=True, upload_to='bid_opportunities/%Y/%m/%d/', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Bid Opportunity',
                'verbose_name_plural': 'Bid Opportunities',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CitizensCharter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Citizens Charter',
                'verbose_name_plural': 'Citizens Charter',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, null=True)),
                ('workemail', models.EmailField(blank=True, max_length=254, null=True)),
                ('organization', models.CharField(blank=True, help_text='School or company name', null=True)),
                ('message', models.TextField(blank=True, help_text='Tell us more about your needs and timeline', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoreValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='mvmcv_files/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Core Values',
                'verbose_name_plural': 'Core Values',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DepedAdvisories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True)),
                ('content', models.CharField(blank=True, help_text='Bold Text: <strong> content... </strong> or <b> content.. </b> | Italicize: <em> content... </em> | <big> content.. </big>]', null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='depedadvisories/')),
            ],
            options={
                'verbose_name': 'Deped Advisories',
                'verbose_name_plural': 'Deped Advisories',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DepedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True)),
                ('content', models.CharField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='depedorder/')),
            ],
            options={
                'verbose_name': 'Deped Order',
                'verbose_name_plural': 'Deped Order',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DivisionMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True)),
                ('content', models.CharField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='divisionmemo/')),
            ],
            options={
                'verbose_name': 'Division Memo',
                'verbose_name_plural': 'Division Memo',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LearningDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='learning_development/%Y/%m/%d/')),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Learning and Development',
                'verbose_name_plural': 'Learning and Development',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='mvmcv_files/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mandate',
                'verbose_name_plural': 'Mandate',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='mvmcv_files/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Mission',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_image')),
                ('file', models.FileField(blank=True, null=True, upload_to='news_files/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OfficeMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True)),
                ('content', models.CharField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='divisionmemo/')),
            ],
            options={
                'verbose_name': 'Ofiice Memo',
                'verbose_name_plural': 'Office Memo',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='orgchart_images/')),
            ],
            options={
                'verbose_name': 'Organizational Chart',
                'verbose_name_plural': 'Organizational Chart',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='performance_management/%Y/%m/%d/')),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Performance Management',
                'verbose_name_plural': 'Performance Management',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='program_image')),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='program_files/')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Program',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='QualityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True)),
                ('content', models.CharField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='qualitypolicy_files/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Quality Policy',
                'verbose_name_plural': 'Quality Policy',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentSelectionPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='primehrm/%Y/%m/%d/')),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recruitment Selection Placement',
                'verbose_name_plural': 'Recruitment Selection Placement',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RegionalMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True)),
                ('content', models.CharField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='regionalmemo/')),
            ],
            options={
                'verbose_name': 'Regional Memo',
                'verbose_name_plural': 'Regional Memo',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RewardsRecognitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Title of the reward/recognition', null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the award', null=True)),
                ('file', models.FileField(blank=True, help_text='Upload supporting document', null=True, upload_to='rewards_recognitions/%Y/%m/%d/')),
                ('link', models.URLField(blank=True, help_text='External URL related to this recognition', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rewards & Recognition',
                'verbose_name_plural': 'Rewards & Recognitions',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, default='DEPED', null=True)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('contact_email', models.EmailField(default='info@deped.gov.ph', max_length=254)),
                ('contact_phone', models.CharField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('quick_links_json', models.TextField(blank=True, default='{}', help_text='JSON format for quick links. Example: {"Bid Opportunities": "/bid-opportunities"}', null=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='mvmcv_files/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vision',
                'verbose_name_plural': 'Vision',
                'ordering': ['-id'],
            },
        ),
    ]
