# Generated by Django 5.2.3 on 2025-06-27 01:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0002_awards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/%y')),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
