# Generated by Django 5.2.3 on 2025-06-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0003_videos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationalchart',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='organizationalchart',
            name='link',
        ),
        migrations.AddField(
            model_name='organizationalchart',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationalchart',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationalchart',
            name='positions',
            field=models.CharField(blank=True, null=True),
        ),
    ]
