# Generated by Django 5.2.3 on 2025-06-27 03:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0004_rename_title_organizationalchart_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True, verbose_name='Link Name')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Link URL')),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
