# Generated by Django 5.2.3 on 2025-06-27 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0005_quicklinks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quicklinks',
            old_name='url',
            new_name='links',
        ),
    ]
