# Generated by Django 5.2.3 on 2025-06-27 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0006_rename_url_quicklinks_links'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcement'},
        ),
    ]
