# Generated by Django 5.2.3 on 2025-06-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0007_alter_announcement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quicklinks',
            name='links',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quicklinks',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
