# Generated by Django 5.2.3 on 2025-06-28 02:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0008_alter_quicklinks_links_alter_quicklinks_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citizenscharter',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Citizens Charter', 'verbose_name_plural': 'Citizens Charter'},
        ),
        migrations.AlterModelOptions(
            name='corevalues',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Core Values', 'verbose_name_plural': 'Core Values'},
        ),
        migrations.AlterModelOptions(
            name='depedadvisories',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Deped Advisories', 'verbose_name_plural': 'Deped Advisories'},
        ),
        migrations.AlterModelOptions(
            name='depedorder',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Deped Order', 'verbose_name_plural': 'Deped Order'},
        ),
        migrations.AlterModelOptions(
            name='divisionmemo',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Division Memo', 'verbose_name_plural': 'Division Memo'},
        ),
        migrations.AlterModelOptions(
            name='mandate',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Mandate', 'verbose_name_plural': 'Mandate'},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Mission', 'verbose_name_plural': 'Mission'},
        ),
        migrations.AlterModelOptions(
            name='officememo',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Ofiice Memo', 'verbose_name_plural': 'Office Memo'},
        ),
        migrations.AlterModelOptions(
            name='organizationalchart',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Organizational Chart', 'verbose_name_plural': 'Organizational Chart'},
        ),
        migrations.AlterModelOptions(
            name='qualitypolicy',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Quality Policy', 'verbose_name_plural': 'Quality Policy'},
        ),
        migrations.AlterModelOptions(
            name='regionalmemo',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Regional Memo', 'verbose_name_plural': 'Regional Memo'},
        ),
        migrations.AlterModelOptions(
            name='vision',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Vision', 'verbose_name_plural': 'Vision'},
        ),
        migrations.RenameField(
            model_name='bidopportunities',
            old_name='published',
            new_name='date_posted',
        ),
        migrations.RemoveField(
            model_name='learningdevelopment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='learningdevelopment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='performancemanagement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='performancemanagement',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='program',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='recruitmentselectionplacement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recruitmentselectionplacement',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='rewardsrecognitions',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rewardsrecognitions',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='awardsnotice',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='citizenscharter',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contact',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='corevalues',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='depedadvisories',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='depedorder',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='divisionmemo',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='learningdevelopment',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mandate',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mission',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='officememo',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='organizationalchart',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='performancemanagement',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='qualitypolicy',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recruitmentselectionplacement',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='regionalmemo',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rewardsrecognitions',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vision',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
