# Generated by Django 5.2.3 on 2025-06-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0009_alter_citizenscharter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitypolicy',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
