# Generated by Django 5.2.3 on 2025-06-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0010_alter_qualitypolicy_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officememo',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Office Memo', 'verbose_name_plural': 'Office Memo'},
        ),
        migrations.AddField(
            model_name='organizationalchart',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationalchart',
            name='management',
            field=models.CharField(blank=True, null=True),
        ),
    ]
