# Generated by Django 5.2.3 on 2025-06-30 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0011_alter_officememo_options_organizationalchart_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quicklinks',
            options={'ordering': ['-date_posted'], 'verbose_name_plural': 'Quick Links'},
        ),
    ]
