# Generated by Django 5.2.3 on 2025-07-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0012_alter_quicklinks_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegionalMemo',
        ),
        migrations.AlterModelOptions(
            name='organizationalchart',
            options={'ordering': ['-date_posted'], 'verbose_name_plural': 'Organizational Charts'},
        ),
        migrations.AlterField(
            model_name='organizationalchart',
            name='contact',
            field=models.CharField(blank=True, null=True),
        ),
    ]
