# Generated by Django 5.2.3 on 2025-07-01 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0013_delete_regionalmemo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationalchart',
            options={'verbose_name_plural': 'Organizational Charts'},
        ),
    ]
