# Generated by Django 5.2.3 on 2025-07-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0014_alter_organizationalchart_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depedadvisories',
            name='content',
            field=models.TextField(blank=True, help_text='Bold Text: <strong> content... </strong> or <b> content.. </b> | Italicize: <em> content... </em> | <big> content.. </big>]', null=True),
        ),
    ]
