# Generated by Django 5.2.3 on 2025-07-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0015_alter_depedadvisories_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidopportunities',
            name='abc',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bidopportunities',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bid_opportunities/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='bidopportunities',
            name='projectname',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bidopportunities',
            name='ref',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
