# Generated by Django 5.2.3 on 2025-07-03 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0016_alter_bidopportunities_abc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date_posted',
        ),
    ]
