# Generated by Django 5.2.3 on 2025-07-03 08:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0017_remove_contact_date_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideosCitizensCharter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/%y')),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='fullname',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(default='', help_text='Tell us more about your needs and timeline'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='organization',
            field=models.CharField(default='', help_text='School or company name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='workemail',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
