# Generated by Django 5.2.3 on 2025-07-04 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0018_videoscitizenscharter_alter_contact_fullname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citizenscharter',
            options={'verbose_name': 'Citizens Charter', 'verbose_name_plural': 'Citizens Charter'},
        ),
    ]
