# Generated by Django 5.2.3 on 2025-07-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0019_alter_citizenscharter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officememo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='officememo/'),
        ),
    ]
