# Generated by Django 5.2.3 on 2025-07-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0020_alter_officememo_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationalchart',
            options={'ordering': ['management', 'positions'], 'verbose_name_plural': 'Organizational Charts'},
        ),
        migrations.AlterField(
            model_name='organizationalchart',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organizationalchart',
            name='management',
            field=models.CharField(blank=True, choices=[('OSDS', 'OSDS'), ('ADMIN', 'Administrative Section'), ('GENERAL', 'General Service'), ('FINANCE', 'Finance'), ('CID', 'Curriculum Implementation Division'), ('ALS', 'Alternative Learning System'), ('SGOD', 'SGOD')], max_length=50, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='organizationalchart',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organizationalchart',
            name='positions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
