# Generated by Django 5.2.3 on 2025-07-04 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0021_alter_organizationalchart_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationalchart',
            options={'ordering': ['positions'], 'verbose_name_plural': 'Organizational Charts'},
        ),
    ]
