# Generated by Django 5.2.3 on 2025-07-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0022_alter_organizationalchart_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalchart',
            name='management',
            field=models.CharField(blank=True, choices=[('OSDS', 'Office of the Schools Division Superintendent'), ('ADMIN', 'Administrative Section'), ('GENERAL', 'General Service'), ('FINANCE', 'Finance'), ('CID', 'Curriculum Implementation Division'), ('ALS', 'Alternative Learning System'), ('SGOD', 'School Governance and Operations Division')], max_length=50, null=True, verbose_name='Department'),
        ),
    ]
