# Generated by Django 5.2.3 on 2025-07-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0023_alter_organizationalchart_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='file',
            field=models.FileField(blank=True, help_text='PDF file only', null=True, upload_to='announcement_files/'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='file',
            field=models.FileField(blank=True, help_text='PDF file only', null=True, upload_to='awards_file'),
        ),
        migrations.AlterField(
            model_name='awardsnotice',
            name='file',
            field=models.FileField(blank=True, help_text='PDF file only', null=True, upload_to='awards_notices/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='bidopportunities',
            name='file',
            field=models.FileField(blank=True, help_text='PDF file only', null=True, upload_to='bid_opportunities/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='citizenscharter',
            name='file',
            field=models.FileField(blank=True, help_text='PDF file only', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='corevalues',
            name='file',
            field=models.FileField(blank=True, help_text='PDF file only', null=True, upload_to='mvmcv_files/'),
        ),
        migrations.AlterField(
            model_name='depedadvisories',
            name='file',
            field=models.FileField(blank=True, help_text='PDF file only', null=True, upload_to='depedadvisories/'),
        ),
        migrations.AlterField(
            model_name='depedorder',
            name='file',
            field=models.FileField(blank=True, help_text='PDF file only', null=True, upload_to='depedorder/'),
        ),
        migrations.AlterField(
            model_name='divisionmemo',
            name='file',
            field=models.FileField(blank=True, help_text='PDF file only', null=True, upload_to='divisionmemo/'),
        ),
        migrations.AlterField(
            model_name='learningdevelopment',
            name='file',
            field=models.FileField(blank=True, help_text='PDF file only', null=True, upload_to='learning_development/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='file',
            field=models.FileField(blank=True, help_text='PDF file only', null=True, upload_to='mvmcv_files/'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='file',
            field=models.FileField(blank=True, help_text='PDF file only', null=True, upload_to='mvmcv_files/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='file',
            field=models.FileField(blank=True, help_text='PDF file only', null=True, upload_to='news_files/'),
        ),
        migrations.AlterField(
            model_name='officememo',
            name='file',
            field=models.FileField(blank=True, help_text='PDF file only', null=True, upload_to='officememo/'),
        ),
        migrations.AlterField(
            model_name='performancemanagement',
            name='file',
            field=models.FileField(blank=True, help_text='PDF file only', null=True, upload_to='performance_management/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='program',
            name='file',
            field=models.FileField(blank=True, help_text='PDF file only', null=True, upload_to='program_files/'),
        ),
        migrations.AlterField(
            model_name='qualitypolicy',
            name='file',
            field=models.FileField(blank=True, help_text='PDF file only', null=True, upload_to='qualitypolicy_files/'),
        ),
        migrations.AlterField(
            model_name='recruitmentselectionplacement',
            name='file',
            field=models.FileField(blank=True, help_text='PDF file only', null=True, upload_to='primehrm/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='rewardsrecognitions',
            name='file',
            field=models.FileField(blank=True, help_text='PDF file only', null=True, upload_to='rewards_recognitions/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='vision',
            name='file',
            field=models.FileField(blank=True, help_text='PDF file only', null=True, upload_to='mvmcv_files/'),
        ),
    ]
