# Generated by Django 5.2.3 on 2025-07-07 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0024_alter_announcement_file_alter_awards_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awards',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Awards', 'verbose_name_plural': 'Awards'},
        ),
        migrations.AlterModelOptions(
            name='awardsnotice',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Learning and Development', 'verbose_name_plural': 'Learning and Development'},
        ),
        migrations.AlterModelOptions(
            name='bidopportunities',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Bid Opportunity', 'verbose_name_plural': 'Bid Opportunities'},
        ),
        migrations.AlterModelOptions(
            name='learningdevelopment',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Learning and Development', 'verbose_name_plural': 'Learning and Development'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date_posted'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='performancemanagement',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Performance Management', 'verbose_name_plural': 'Performance Management'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Program', 'verbose_name_plural': 'Program'},
        ),
        migrations.AlterModelOptions(
            name='recruitmentselectionplacement',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Recruitment Selection Placement', 'verbose_name_plural': 'Recruitment Selection Placement'},
        ),
        migrations.AlterModelOptions(
            name='rewardsrecognitions',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Rewards & Recognition', 'verbose_name_plural': 'Rewards & Recognitions'},
        ),
    ]
