# Generated by Django 5.2.3 on 2025-07-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0025_alter_awards_options_alter_awardsnotice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depedorder',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='divisionmemo',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officememo',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
