# Generated by Django 5.2.3 on 2025-07-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0026_alter_depedorder_content_alter_divisionmemo_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoscitizenscharter',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
