# Generated by Django 5.2.3 on 2025-07-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0027_videoscitizenscharter_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalchart',
            name='contact',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationalchart',
            name='management',
            field=models.CharField(blank=True, choices=[('OSDS', 'Office of the Schools Division Superintendent'), ('ADMIN', 'Administrative Section'), ('GENERAL', 'General Service'), ('FINANCE', 'Finance'), ('CID', 'Curriculum Implementation Division'), ('ALS', 'Alternative Learning System'), ('SGOD', 'School Governance and Operations Division')], null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='organizationalchart',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationalchart',
            name='positions',
            field=models.CharField(blank=True, null=True),
        ),
    ]
