# Generated by Django 5.2.3 on 2025-07-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0028_alter_organizationalchart_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationalchart',
            options={'ordering': ['management', 'priority', 'name'], 'verbose_name_plural': 'Organizational Charts'},
        ),
        migrations.AddField(
            model_name='organizationalchart',
            name='priority',
            field=models.IntegerField(blank=True, help_text='Automatically set based on position hierarchy', null=True),
        ),
        migrations.AddIndex(
            model_name='organizationalchart',
            index=models.Index(fields=['management'], name='deped_app_o_managem_3fe40c_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationalchart',
            index=models.Index(fields=['positions'], name='deped_app_o_positio_5a02b6_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationalchart',
            index=models.Index(fields=['priority'], name='deped_app_o_priorit_3bc202_idx'),
        ),
    ]
