# Generated by Django 5.2.3 on 2025-07-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0029_alter_organizationalchart_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeFormSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')])),
                ('customer_type', models.CharField(choices=[('Business', 'Business (private school, corporations, etc.)'), ('Citizen', 'Citizen (general public, learners, parents, former DepEd employees, researchers, NGOs etc.)'), ('Government Government', 'Government Government (current DepEd employees or employees of other government agencies & LGUs)')])),
                ('office_transacted', models.CharField(choices=[('SDS', 'Schools Division Superintendent'), ('ASDS', 'Assistant Schools Division Superintendent'), ('Admin', 'Cash, Personnel, Records, Supply, General Services, Procurement'), ('CID', 'Curriculum Implementation Division'), ('Finance', 'Accounting, Budget'), ('ICT', 'ICT'), ('Legal', 'Legal'), ('SGOD', 'School Governance and Operations Division')])),
                ('service_availed_sds', models.CharField(choices=[('Travel Authority', 'Travel Authority'), ('Other requests/inquiries', 'Other requests/inquiries'), ('Feedback/Complaint', 'Feedback/Complaint')])),
                ('citizens_charter', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')])),
                ('sqd', models.CharField(choices=[('Strongly Agree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neither Agree nor Disagree', 'Neither Agree nor Disagree'), ('Disagree', 'Disagree'), ('Strongly Disagree', 'Strongly Disagree'), ('Not Applicable', 'Not Applicable')])),
                ('remarks', models.TextField()),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Office Form Survey',
                'verbose_name_plural': 'Office Form Surveys',
                'ordering': ['-submission_date'],
            },
        ),
    ]
