# Generated by Django 5.2.3 on 2025-07-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0030_officeformsurvey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeformsurvey',
            name='sqd',
            field=models.CharField(choices=[('Strongly Agree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neither Agree nor Disagree', 'Neither Agree nor Disagree'), ('Disagree', 'Disagree'), ('Strongly Disagree', 'Strongly Disagree'), ('Not Applicable', 'Not Applicable')], default='Neither Agree nor Disagree'),
        ),
    ]
