# Generated by Django 5.2.3 on 2025-07-09 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0031_alter_officeformsurvey_sqd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officeformsurvey',
            name='sqd',
        ),
        migrations.AddField(
            model_name='officeformsurvey',
            name='sqd1',
            field=models.IntegerField(choices=[(5, '5 (Strongly Agree)'), (4, '4 (Agree)'), (3, '3 (Neutral)'), (2, '2 (Disagree)'), (1, '1 (Strongly Disagree)')], default=3, verbose_name='Time spent for transaction was acceptable'),
        ),
        migrations.AddField(
            model_name='officeformsurvey',
            name='sqd2',
            field=models.IntegerField(choices=[(5, '5 (Strongly Agree)'), (4, '4 (Agree)'), (3, '3 (Neutral)'), (2, '2 (Disagree)'), (1, '1 (Strongly Disagree)')], default=3, verbose_name='Requirements and steps were clear'),
        ),
        migrations.AddField(
            model_name='officeformsurvey',
            name='sqd3',
            field=models.IntegerField(choices=[(5, '5 (Strongly Agree)'), (4, '4 (Agree)'), (3, '3 (Neutral)'), (2, '2 (Disagree)'), (1, '1 (Strongly Disagree)')], default=3, verbose_name='Staff were competent and knowledgeable'),
        ),
        migrations.AddField(
            model_name='officeformsurvey',
            name='sqd4',
            field=models.IntegerField(choices=[(5, '5 (Strongly Agree)'), (4, '4 (Agree)'), (3, '3 (Neutral)'), (2, '2 (Disagree)'), (1, '1 (Strongly Disagree)')], default=3, verbose_name='Staff were courteous and approachable'),
        ),
        migrations.AddField(
            model_name='officeformsurvey',
            name='sqd5',
            field=models.IntegerField(choices=[(5, '5 (Strongly Agree)'), (4, '4 (Agree)'), (3, '3 (Neutral)'), (2, '2 (Disagree)'), (1, '1 (Strongly Disagree)')], default=3, verbose_name='Facilities were adequate and comfortable'),
        ),
        migrations.AddField(
            model_name='officeformsurvey',
            name='sqd6',
            field=models.IntegerField(choices=[(5, '5 (Strongly Agree)'), (4, '4 (Agree)'), (3, '3 (Neutral)'), (2, '2 (Disagree)'), (1, '1 (Strongly Disagree)')], default=3, verbose_name='Overall satisfaction with the service'),
        ),
        migrations.AddField(
            model_name='officeformsurvey',
            name='sqd7',
            field=models.IntegerField(choices=[(5, '5 (Strongly Agree)'), (4, '4 (Agree)'), (3, '3 (Neutral)'), (2, '2 (Disagree)'), (1, '1 (Strongly Disagree)')], default=3, verbose_name='Would recommend this office to others'),
        ),
        migrations.AddField(
            model_name='officeformsurvey',
            name='sqd8',
            field=models.IntegerField(choices=[(5, '5 (Strongly Agree)'), (4, '4 (Agree)'), (3, '3 (Neutral)'), (2, '2 (Disagree)'), (1, '1 (Strongly Disagree)')], default=3, verbose_name='The service met my expectations'),
        ),
        migrations.AlterField(
            model_name='officeformsurvey',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='officeformsurvey',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
