# Generated by Django 5.2.3 on 2025-07-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0032_remove_officeformsurvey_sqd_officeformsurvey_sqd1_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='officeformsurvey',
            index=models.Index(fields=['submission_date'], name='deped_app_o_submiss_609ced_idx'),
        ),
        migrations.AddIndex(
            model_name='officeformsurvey',
            index=models.Index(fields=['office_transacted'], name='deped_app_o_office__f9aac4_idx'),
        ),
        migrations.AddIndex(
            model_name='officeformsurvey',
            index=models.Index(fields=['customer_type'], name='deped_app_o_custome_24efd5_idx'),
        ),
    ]
