# Generated by Django 5.2.3 on 2025-07-10 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0033_officeformsurvey_deped_app_o_submiss_609ced_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfficeFormSurvey',
        ),
    ]
