# Generated by Django 5.2.3 on 2025-07-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0034_delete_officeformsurvey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='divisionmemo',
            options={'ordering': ['-year', '-month', '-date_posted'], 'verbose_name': 'Division Memo', 'verbose_name_plural': 'Division Memo'},
        ),
        migrations.AddField(
            model_name='divisionmemo',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=7),
        ),
        migrations.AddField(
            model_name='divisionmemo',
            name='year',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030)], default=2025),
        ),
    ]
