# Generated by Django 5.2.3 on 2025-07-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0037_alter_divisionmemo_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalchart',
            name='org_chart_image',
            field=models.ImageField(blank=True, null=True, upload_to='orgchart_images/'),
        ),
    ]
