# Generated by Django 5.2.3 on 2025-07-12 17:09

import deped_app.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0039_alter_depedadvisories_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awardsnotice',
            options={'ordering': ['-date_published'], 'verbose_name': 'Learning and Development', 'verbose_name_plural': 'Learning and Development'},
        ),
        migrations.AlterModelOptions(
            name='bidopportunities',
            options={'ordering': ['-date_published'], 'verbose_name': 'Bid Opportunity', 'verbose_name_plural': 'Bid Opportunities'},
        ),
        migrations.AlterModelOptions(
            name='learningdevelopment',
            options={'ordering': ['-date_published'], 'verbose_name': 'Learning and Development', 'verbose_name_plural': 'Learning and Development'},
        ),
        migrations.AlterModelOptions(
            name='performancemanagement',
            options={'ordering': ['-date_published'], 'verbose_name': 'Performance Management', 'verbose_name_plural': 'Performance Management'},
        ),
        migrations.AlterModelOptions(
            name='recruitmentselectionplacement',
            options={'ordering': ['-date_published'], 'verbose_name': 'Recruitment Selection Placement', 'verbose_name_plural': 'Recruitment Selection Placement'},
        ),
        migrations.AlterModelOptions(
            name='rewardsrecognitions',
            options={'ordering': ['-date_published'], 'verbose_name': 'Rewards & Recognition', 'verbose_name_plural': 'Rewards & Recognitions'},
        ),
        migrations.RemoveField(
            model_name='awardsnotice',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='bidopportunities',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='depedadvisories',
            name='content',
        ),
        migrations.RemoveField(
            model_name='depedadvisories',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='depedorder',
            name='content',
        ),
        migrations.RemoveField(
            model_name='depedorder',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='divisionmemo',
            name='content',
        ),
        migrations.RemoveField(
            model_name='divisionmemo',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='learningdevelopment',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='learningdevelopment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='officememo',
            name='content',
        ),
        migrations.RemoveField(
            model_name='officememo',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='performancemanagement',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='performancemanagement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recruitmentselectionplacement',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='recruitmentselectionplacement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='rewardsrecognitions',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='rewardsrecognitions',
            name='description',
        ),
        migrations.AddField(
            model_name='awardsnotice',
            name='date_published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bidopportunities',
            name='date_published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='depedadvisories',
            name='date_published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='depedorder',
            name='date_published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='divisionmemo',
            name='date_published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='learningdevelopment',
            name='date_published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='officememo',
            name='date_published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='performancemanagement',
            name='date_published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recruitmentselectionplacement',
            name='date_published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rewardsrecognitions',
            name='date_published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='depedadvisories',
            name='file',
            field=models.FileField(default='default.pdf', help_text='PDF file only', storage=deped_app.models.YearMonthFileStorage(), upload_to='depedadvisories/'),
        ),
        migrations.AlterField(
            model_name='depedorder',
            name='file',
            field=models.FileField(default='default.pdf', help_text='PDF file only', storage=deped_app.models.YearMonthFileStorage(), upload_to='depedorder/'),
        ),
        migrations.AlterField(
            model_name='divisionmemo',
            name='file',
            field=models.FileField(default='default.pdf', help_text='PDF file only', storage=deped_app.models.YearMonthFileStorage(), upload_to='divisionmemo/'),
        ),
        migrations.AlterField(
            model_name='learningdevelopment',
            name='file',
            field=models.FileField(blank=True, default='default.pdf', help_text='PDF file only', null=True, upload_to='learning_development/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='officememo',
            name='file',
            field=models.FileField(default='default.pdf', help_text='PDF file only', storage=deped_app.models.YearMonthFileStorage(), upload_to='officememo/'),
        ),
        migrations.AlterField(
            model_name='performancemanagement',
            name='file',
            field=models.FileField(blank=True, default='default.pdf', help_text='PDF file only', null=True, upload_to='performance_management/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='recruitmentselectionplacement',
            name='file',
            field=models.FileField(blank=True, default='default.pdf', help_text='PDF file only', null=True, upload_to='primehrm/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='rewardsrecognitions',
            name='file',
            field=models.FileField(default='default.pdf', upload_to='rewards_recognitions/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='rewardsrecognitions',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rewardsrecognitions',
            name='title',
            field=models.CharField(blank=True, null=True),
        ),
    ]
