# Generated by Django 5.2.3 on 2025-07-12 17:11

import deped_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0040_alter_awardsnotice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depedadvisories',
            name='file',
            field=models.FileField(help_text='PDF file only', storage=deped_app.models.YearMonthFileStorage(), upload_to='depedadvisories/'),
        ),
        migrations.AlterField(
            model_name='depedorder',
            name='file',
            field=models.FileField(help_text='PDF file only', storage=deped_app.models.YearMonthFileStorage(), upload_to='depedorder/'),
        ),
        migrations.AlterField(
            model_name='divisionmemo',
            name='file',
            field=models.FileField(help_text='PDF file only', storage=deped_app.models.YearMonthFileStorage(), upload_to='divisionmemo/'),
        ),
        migrations.AlterField(
            model_name='learningdevelopment',
            name='file',
            field=models.FileField(blank=True, help_text='PDF file only', null=True, upload_to='learning_development/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='officememo',
            name='file',
            field=models.FileField(help_text='PDF file only', storage=deped_app.models.YearMonthFileStorage(), upload_to='officememo/'),
        ),
        migrations.AlterField(
            model_name='performancemanagement',
            name='file',
            field=models.FileField(blank=True, help_text='PDF file only', null=True, upload_to='performance_management/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='recruitmentselectionplacement',
            name='file',
            field=models.FileField(blank=True, help_text='PDF file only', null=True, upload_to='primehrm/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='rewardsrecognitions',
            name='file',
            field=models.FileField(upload_to='rewards_recognitions/%Y/%m/%d/'),
        ),
    ]
