# Generated by Django 5.2.3 on 2025-07-14 04:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deped_app', '0041_alter_depedadvisories_file_alter_depedorder_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgChartWhole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_chart_image', models.ImageField(blank=True, null=True, upload_to='orgchart_images/')),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='organizationalchart',
            name='org_chart_image',
        ),
    ]
